-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce-hufsonian`;

CREATE SCHEMA `ecommerce-hufsonian`;
USE `ecommerce-hufsonian`;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce-hufsonian`.`product_category` (
                                                                         `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
                                                                         `category_name` VARCHAR(255) NULL DEFAULT NULL,
                                                                         PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce-hufsonian`.`product` (
                                                                `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
                                                                `sku` VARCHAR(255) DEFAULT NULL,
                                                                `name` VARCHAR(1024) DEFAULT NULL,
                                                                `description` VARCHAR(2048) DEFAULT NULL,
                                                                `unit_price` DECIMAL(13,2) DEFAULT NULL,
                                                                `image_url` VARCHAR(255) DEFAULT NULL,
                                                                `active` BIT DEFAULT 1,
                                                                `units_in_stock` INT(11) DEFAULT NULL,
                                                                `date_created` DATETIME(6) DEFAULT NULL,
                                                                `last_updated` DATETIME(6) DEFAULT NULL,
                                                                `category_id` BIGINT(20) NOT NULL,
                                                                PRIMARY KEY (`id`),
                                                                KEY `fk_category` (`category_id`),
                                                                CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Philosophy');
INSERT INTO product_category(category_name) VALUES ('History');
INSERT INTO product_category(category_name) VALUES ('Technology');
INSERT INTO product_category(category_name) VALUES ('Literature');

-- -----------------------------------------------------
-- Philosophy
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1000', 'What Does It All Mean?', 'In this cogent and accessible introduction to philosophy, the distinguished author of Mortal Questions and The View From Nowhere sets forth the central problems of philosophical inquiry for the beginning student.', 'assets/images/products/philosophy/PHILOSOPHY-1000.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1001', 'The Life You Can Save: How To Do Your Part To End World Poverty', 'In this Tenth Anniversary Edition of The Life You Can Save, Peter Singer brings his landmark book up to date. In addition to restating his compelling arguments about how we should respond to extreme poverty, he examines the progress we are making and recounts how the first edition transformed the lives both of readers and the people they helped.', 'assets/images/products/philosophy/PHILOSOPHY-1001.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1002', 'Justice: What''s the Right Thing to Do?', 'Considering the role of justice in our society and our lives, Michael Sandel reveals how an understanding of philosophy can help to make sense of politics, religion, morality - and our own convictions.', 'assets/images/products/philosophy/PHILOSOPHY-1002.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1003', 'The Grasshopper - Third Edition: Games, Life and Utopia', 'Through the jocular voice of Aesop''s Grasshopper, a “shiftless but thoughtful practitioner of applied entomology,” Suits not only argues that games can be meaningfully defined; he also suggests that playing games is a central part of the ideal of human existence, and so games belong at the heart of any vision of Utopia.', 'assets/images/products/philosophy/PHILOSOPHY-1003.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1004', 'Being You: A New Science of Consciousness', 'Being You is an engaging and accessible tour through the field’s boldest theories, most creative experiments and most surprising findings. You could give the book to a smart teenager and get them asking questions that they will be thinking about for the rest of their lives.', 'assets/images/products/philosophy/PHILOSOPHY-1004.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1005', 'Hannah Arendt (Critical Lives)', 'As Hill points out in Hannah Arendt, even in works such as The Origins of Totalitarianism—surprise bestseller of the Trump era—the political is invariably brought back to the personal.', 'assets/images/products/philosophy/PHILOSOPHY-1005.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1006', 'The Case for Rage: Why Anger Is Essential to Anti-Racist Struggle', 'Myisha Cherry argues very plausibly that anger is an appropriate, useful, and powerful reaction to racism, and often more effective than cooler responses might be ... When bad people get angry we are in trouble. Of course. But when good people are angry about things that matter there is hope for change.', 'assets/images/products/philosophy/PHILOSOPHY-1006.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1007', 'Four Thousand Weeks: Time Management for Mortals', '[Four Thousand Weeks] is perfectly pitched somewhere between practical self-help book and philosophical quest . . . As with all the best quests, its many pleasures don''t require a fast-forward button, but happen along the way.', 'assets/images/products/philosophy/PHILOSOPHY-1007.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1008', 'Free: A Child and a Country at the End of History', 'Free is one of those very rare books that shows how history shapes people’s lives and their politics. Lea Ypi is such a brilliant, powerful writer that her story becomes your story.', 'assets/images/products/philosophy/PHILOSOPHY-1008.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1009', 'Nietzsche : A Philosophical Biography', 'In the first major biography in decades, Safranski re-creates the anguished life of Nietzsche while simultaneously assessing the philosophical implications of his morality, religion, and art.', 'assets/images/products/philosophy/PHILOSOPHY-1009.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1010', 'Nietzsche on Truth and Philosophy (Modern European Philosophy)', 'Maudemarie Clark''s highly original study gives a lucid and penetrating analytical account of all the central topics of Nietzsche''s epistemology and metaphysics, including his views on truth and language, his perspectivism, and his doctrines of the will-to-power and the eternal recurrence.', 'assets/images/products/philosophy/PHILOSOPHY-1010.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1011', 'Analects: With Selections from Traditional Commentaries', 'Contemporary readers will be enlightened as to what Confucius taught his disciples and will share the experience of being a neighbor to all the generations of students who have pondered the sometimes cryptic and enigmatic words of Confucius. Slingerland''s use of commentary gives readers a fighting chance at understanding and appreciating this foundational Confucian classic.', 'assets/images/products/philosophy/PHILOSOPHY-1011.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1012', 'Political Dissent in Democratic Athens: Intellectual Critics of Popular Rule', 'Ober offers fresh readings of the political works of Thucydides, Plato, and Aristotle, among others, by placing them in the context of a competitive community of dissident writers. These thinkers struggled against both democratic ideology and intellectual rivals to articulate the best and most influential criticism of popular rule. ', 'assets/images/products/philosophy/PHILOSOPHY-1012.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1013', 'The Republic (Penguin Classics)', 'The Republic also addresses the purpose of education and the role of both women and men as "guardians" of the people. With remarkable lucidity and deft use of allegory, Plato arrives at a depiction of a state bound by harmony and ruled by "philosopher kings."', 'assets/images/products/philosophy/PHILOSOPHY-1013.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1014', 'Why Plato Wrote', 'In this groundbreaking book Danielle Allen gives us Plato for the 21st century: a boldly pragmatic and fiercely political philosopher, a ‘legislator of the world’ whose vivid writing reframed the moral practices of real communities, a provocative and successful linguistic entrepreneur whose Socratic dialogues sparked a culture war that defined Athenian politics in the Age of Alexander.', 'assets/images/products/philosophy/PHILOSOPHY-1014.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1015', 'The Collected Works of Spinoza, Volume I', 'The Collected Works of Spinoza provides, for the first time in English, a truly satisfactory edition of all of Spinoza''s writings, with accurate and readable translations, based on the best critical editions of the original-language texts, done by a scholar who has published extensively on the philosopher''s work.', 'assets/images/products/philosophy/PHILOSOPHY-1015.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1016', 'Behind the Geometrical Method: A Reading of Spinoza''s Ethics', 'This book is the fruit of twenty-five years of study of Spinoza by the editor and translator of a new and widely acclaimed edition of Spinoza''s collected works. ', 'assets/images/products/philosophy/PHILOSOPHY-1016.png', 1, 100, 27.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1017', 'The Human Condition: Second Edition', 'A great work of the mind and the imagination. . . . Arendt has done even more to prise open our oyster minds than she did in The Origins of Totalitarianism.', 'assets/images/products/philosophy/PHILOSOPHY-1017.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1018', 'David Hume: A Treatise Of Human Nature: Volume 1', 'David and Mary Norton present the definitive scholarly edition of one of the greatest philosophical works ever written. This first volume contains the critical text of David Hume''s Treatise of Human Nature (1739/40), followed by the short Abstract (1740) in which Hume set out the key arguments of the larger work', 'assets/images/products/philosophy/PHILOSOPHY-1018.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1019', 'Tractatus Logico-Philosophicus (Routledge Classics)', 'Perhaps the most important work of philosophy written in the twentieth century, Tractatus Logico-Philosophicus was the only philosophical work that Ludwig Wittgenstein published during his lifetime. Written in short, carefully numbered paragraphs of extreme brilliance, it captured the imagination of a generation of philosophers.', 'assets/images/products/philosophy/PHILOSOPHY-1019.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1020', 'Philosophy of Logic: Second Edition', 'Quine pursues his philosophical vision with an uncompromising consistency of purpose that makes his doctrines impossible to ignore. You either go with him or define your position in reaction to his. And this is one mark of a great philosopher.', 'assets/images/products/philosophy/PHILOSOPHY-1020.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1021', 'Notebooks, 1935-1942 (Volume 1)', 'From 1935 until his death, Albert Camus kept a series of notebooks to sketch out ideas for future works, record snatches of conversations and excerpts from books he was reading, and jot down his reflections on death and the horror of war, his feelings about women and loneliness and art, and his appreciations for the Algerian sun and sea.', 'assets/images/products/philosophy/PHILOSOPHY-1021.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1022', 'Language, Truth and Logic', 'Mr. Ayers sets up specific tests by which you can easily evaluate statements of ideas. You will also learn how to distinguish ideas that cannot be verified by experience — those expressing religious, moral, or aesthetic experience, those expounding theological or metaphysical doctrine, and those dealing with a priori truth. ', 'assets/images/products/philosophy/PHILOSOPHY-1022.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1023', 'Avicenna (Great Medieval Thinkers)', 'In Avicenna Jon McGinnis provides a general introduction to the thinker''s intellectual system and offers a careful philosophical analysis of major aspects of his work in clear prose that will be accessible to students as well as to specialists in Islamic studies, philosophy, and the history of science.', 'assets/images/products/philosophy/PHILOSOPHY-1023.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('PHILOSOPHY-1024', 'Mind the Body: An Exploration of Bodily Self-Awareness', 'This volume combines philosophical analysis with recent experimental results from cognitive science, leading us to question some of our most basic intuitions.', 'assets/images/products/philosophy/PHILOSOPHY-1024.png', 1, 100, 16.99, 1, NOW());

# -- -----------------------------------------------------
# -- History
# -- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('HISTORY-1000', 'What Is History?', 'Professor Carr shows that the ''facts'' of history are simply those which historians have selected for scrutiny. Millions have crossed the Rubicon, but the historians tell us that only Caesar''s crossing was significant. All historical facts come to us as a result of interpretative choices by historians influenced by the standards of their age. Yet if absolute objectivity is impossible, the role of the historian need in no way suffer; nor does history lose its fascination.', 'assets/images/products/history/HISTORY-1000.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('HISTORY-1001', '1491: New Revelations of the Americas Before Columbus', 'A ripping, man-on-the-ground tour of a world most of us barely intuit.... An exhilarating shift in perspective.... 1491 erases our myth of a wilderness Eden. It replaces that fallacy with evidence of a different genesis, exciting and closer to true.', 'assets/images/products/history/HISTORY-1001.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('HISTORY-1002', 'Precolonial Black Africa', 'This comparison of the political and social systems of Europe and black Africa from antiquity to the formation of modern states demonstrates the black contribution to the development of Western civilization.', 'assets/images/products/history/HISTORY-1002.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('HISTORY-1003', 'The Guns of August: The Pulitzer Prize-Winning Classic About the Outbreak of World War I', '“A brilliant piece of military history which proves up to the hilt the force of Winston Churchill’s statement that the first month of World War I was ‘a drama never surpassed.’”—Newsweek', 'assets/images/products/history/HISTORY-1003.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('HISTORY-1004', 'Parallel Lives Vol. 1', 'Plutarch''s Lives of the Noble Greeks and Romans, commonly called Parallel Lives or Plutarch''s Lives, is a series of biographies of famous men, arranged in tandem to illuminate their common moral virtues or failings. The surviving Parallel Lives, contain twenty-three pairs of biographies, each pair consisting of one Greek and one Roman, as well as four unpaired, single lives. It is a work of considerable importance.', 'assets/images/products/history/HISTORY-1004.png', 1, 100, 18.99, 2, NOW());

# -- -----------------------------------------------------
# -- Technology
# -- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TECHNOLOGY-1000', 'Big Tech''s Battle to Erase the Trump Movement and Steal the Election', 'They reveal secret methods to covertly manipulate online information without us ever being aware of it, explaining how tech companies can use big data to target undecided voters. They lift the lid on a plot four years in the making—a plot to use the power of technology to stop Donald Trump''s re-election.', 'assets/images/products/technology/TECHNOLOGY-1000.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TECHNOLOGY-1001', 'Rage Inside the Machine: The Prejudice of Algorithms, and How to Stop the Internet Making Bigots of Us All', 'This book demonstrates how non-scientific ideas have been encoded deep into our technological infrastructure. Offering a rigorous, fresh perspective on how technology has brought us to this place, Rage Inside the Machine challenges the long-held assumption that technology is an apolitical and amoral force.', 'assets/images/products/technology/TECHNOLOGY-1001.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TECHNOLOGY-1002', 'Army of None: Autonomous Weapons and the Future of War', 'Scharre’s far-ranging investigation examines the emergence of autonomous weapons, the movement to ban them, and the legal and ethical issues surrounding their use. He spotlights artificial intelligence in military technology, spanning decades of innovation from German noise-seeking Wren torpedoes in World War II', 'assets/images/products/technology/TECHNOLOGY-1002.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TECHNOLOGY-1003', 'A World Without Work: Technology, Automation, and How We Should Respond', '“An important book on an equally important topic. Susskind’s conclusion is that ultimately there will be less paid work to go around. This will shake the foundations of our economy and our society. It will be a daunting challenge. We have to start thinking hard about it now.”', 'assets/images/products/technology/TECHNOLOGY-1003.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TECHNOLOGY-1004', 'Enterprise Artificial Intelligence Transformation', 'Author Rashed Haq is a subject matter expert on AI, having developed AI and data science strategies, platforms, and applications for Publicis Sapient''s clients for over 10 years. He shares that expertise in the new book, Enterprise Artificial Intelligence Transformation.', 'assets/images/products/technology/TECHNOLOGY-1004.png', 1, 100, 17.99, 3, NOW());

# -- -----------------------------------------------------
# -- Literature
# -- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LITERATURE-1000', 'Pride and Prejudice', 'Few have failed to be charmed by the witty and independent spirit of Elizabeth Bennet in Austen’s beloved classic Pride and Prejudice. When Elizabeth Bennet first meets eligible bachelor Fitzwilliam Darcy, she thinks him arrogant and conceited; he is indifferent to her good looks and lively mind. When she later discovers that Darcy has involved himself in the troubled relationship between his friend Bingley and her beloved sister Jane, she is determined to dislike him more than ever. In the sparkling comedy of manners that follows, Jane Austen shows us the folly of judging by first impressions and superbly evokes the friendships, gossip and snobberies of provincial middle-class life. This Penguin Classics edition, based on Austen''s first edition, contains the original Penguin Classics introduction by Tony Tanner and an updated introduction and notes by Viven Jones.', 'assets/images/products/literature/LITERATURE-1000.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LITERATURE-1001', 'The Great Gatsby: A Classic 1925 Jazz Age Novel', 'The Great Gatsby is a Great American Novel of the 20th century. Set in the Jazz Age on Long Island, near New York City, The Great Gatsby depicts the tragic story of Jay Gatsby, a self-made millionaire, and his pursuit of Daisy Buchanan, a wealthy young woman who is his former lover.', 'assets/images/products/literature/LITERATURE-1001.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LITERATURE-1002', 'Othello', 'The Tragedy of Othello, the Moor of Venice is a tragedy by William Shakespeare, believed to have been written in the year approximately 1603, and based on the short story Un Capitano Moro ("A Moorish Captain") by Cinthio, a disciple of Boccaccio, first published in 1565.', 'assets/images/products/literature/LITERATURE-1002.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LITERATURE-1003', 'The Metamorphosis', '"The Metamorphosis" (original German title: "Die Verwandlung") is a short novel by Franz Kafka, first published in 1915. It is often cited as one of the seminal works of fiction of the 20th century and is widely studied in colleges and universities across the western world. The story begins with a traveling salesman, Gregor Samsa, waking to find himself transformed into an insect.', 'assets/images/products/literature/LITERATURE-1003.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LITERATURE-1004', 'The Castle', 'Left unfinished by Kafka in 1922 and not published until 1926, two years after his death, The Castle is the haunting tale of K.’s relentless, unavailing struggle with an inscrutable authority in order to gain access to the Castle. Scrupulously following the fluidity and breathlessness of the sparsely punctuated original manuscript, Mark Harman’s new translation reveals levels of comedy, energy, and visual power previously unknown to English language readers.', 'assets/images/products/literature/LITERATURE-1004.png', 1, 100, 16.99, 4, NOW());

